import "../globals.css";
import { ToastContainer } from "react-toastify";
import { AdminContextProvider } from "./AdminContext";

export const metadata = {
  title: "Admin",
  description: "Generated by create next app",
};

export default function AdminLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <AdminContextProvider>
          <ToastContainer/>
          {children}
          </AdminContextProvider>
      </body>
    </html>
  );
}
