import "../globals.css";
import { ToastContainer } from "react-toastify";
import Provider from "../(home)/provider";

export const metadata = {
  title: "Reset-Password",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <Provider>
          <ToastContainer/>
          {children}
        </Provider>

      </body>
    </html>
  );
}