import "../globals.css";
import Navbar from "@/components/Navbar";
import Provider from "./provider";
import { ToastContainer } from "react-toastify";
import Footer from "@/components/Footer";
import RootContextPovider from "@/constextApi/Context";
export const metadata = {
  title: "Justice",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <Provider>
          <RootContextPovider>
          <Navbar/>
          <ToastContainer/>
          {children}
          <Footer/>
          </RootContextPovider>
        </Provider>
      </body>
    </html>
  );
}
